/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PokemonEvolutionHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import util.IConstants;

/**
 *
 * @author Nelson
 */
public class EvolutionView extends javax.swing.JInternalFrame implements Runnable, IConstants{

    private String pokemonImagePath;
    private String pokemonEvolutionImagePath;
    private PokemonEvolutionHandler evolutionHandler;
    
    public EvolutionView(String pPokemonImagePath, String pPokemonEvolutionImagePath) {
        initComponents();
        this.pokemonImagePath = pPokemonImagePath;
        this.pokemonEvolutionImagePath = pPokemonEvolutionImagePath;
        this.evolutionHandler = new PokemonEvolutionHandler();
        this.setTitle("Evolución pokemon                                                       ");
        this.setResizable(false);
    }
    
    @Override
    public void run() {
        try {
            this.pokemonImageLabel.setIcon(new ImageIcon(getClass().getResource(this.pokemonImagePath)));
            Thread.sleep(3000);
            this.evolutionAnimation.setIcon(new ImageIcon(getClass().getResource(URL_GIF)));        
            Thread.sleep(3000);
            this.evolutionAnimation.setVisible(false);
            this.pokemonImageLabel.setIcon(new ImageIcon(getClass().getResource(this.pokemonEvolutionImagePath)));
            Thread.sleep(3000);                        
            evolutionHandler.setChanged(true);
            this.dispose();
        } catch (InterruptedException ex) {
            Logger.getLogger(EvolutionView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public PokemonEvolutionHandler getEvolutionHandler() {
        return evolutionHandler;
    }

    public void setEvolutionHandler(PokemonEvolutionHandler evolutionHandler) {
        this.evolutionHandler = evolutionHandler;
    }        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        evolutionAnimation = new javax.swing.JLabel();
        pokemonImageLabel = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setPreferredSize(new java.awt.Dimension(350, 300));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanel1.setLayout(null);

        evolutionAnimation.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel1.add(evolutionAnimation);
        evolutionAnimation.setBounds(10, 0, 300, 300);

        pokemonImageLabel.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel1.add(pokemonImageLabel);
        pokemonImageLabel.setBounds(130, 70, 200, 200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel evolutionAnimation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pokemonImageLabel;
    // End of variables declaration//GEN-END:variables
}
