package view;

import controller.Client;
import controller.OriginPlayerHandler;
import Domain.Player;
import Domain.Pokemon;
import controller.ForeignPlayerHandler;
import java.awt.Color;
import java.util.Observable;
import java.util.Observer;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import util.IConstants;

/**
 *
 * @author Nelson
 */
public class PrincipalWindow extends javax.swing.JFrame implements Observer, IConstants {

    private JLabel[][] pokemonOringinImages;
    private JLabel[][] pokemonOriginNames;
    private JLabel[][] pokemonForeignImages;
    private JLabel[][] pokemonForeignNames;
    
    private JPanel[][] selectOriginPokemon;
    private JPanel[][] selectForeignPokemon;

    private int originCoachNumber;
    private int foreignCoachNumber;
    
    private Player originCoach;
    private Player foreighCoach;
    
    private Client client;
    
    private Pokemon[][] pokedexOrigin;
    private Pokemon[][] pokedexForeign;

    /**
     * Creates new form PrincipalWindow
     */
    public PrincipalWindow() {
        initComponents();
        initial();
    }

    private void initial() {
        this.setSize(1024, 720);
        this.setLocationRelativeTo(null);
        enterExistingPlayerPane.setVisible(false);
        createPlayerPane.setVisible(false);
        originPlayerPokemonsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int i = evt.getX() / 150;
                int j = evt.getY() / 150;

                for (JPanel[] selectOriginPokemon1 : selectOriginPokemon) {
                    for (int l = 0; l < selectOriginPokemon[0].length; l++) {
                        selectOriginPokemon1[l].setBorder(null);
                    }
                }
                selectOriginPokemon[i][j].setBorder(BorderFactory.createLineBorder(Color.red));
                originPokemonName.setText("Nombre: " + pokedexOrigin[i][j].getName());
                originPokemonType1.setText("Tipo 1: " + pokedexOrigin[i][j].getType1());
                originPokemonType2.setText("Tipo 2: " + pokedexOrigin[i][j].getType2());
                originPokemonEggGroup1.setText("Huevo grupo 1: " + pokedexOrigin[i][j].getEggGroup1());
                originPokemonEggGroup2.setText("Huevo grupo 2: " + pokedexOrigin[i][j].getEggGroup2());
                originPokemonOriginalCoach.setText("Entrenador original: " + pokedexOrigin[i][j].getOriginalCoach());
                originPokemonCoach.setText("Entrenador actual: " + pokedexOrigin[i][j].getCoach());
            }
        });

        foreingPlayerPokemonsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int i = evt.getX() / 150;
                int j = evt.getY() / 150;

                for (JPanel[] selectForeignPokemon1 : selectForeignPokemon) {
                    for (int l = 0; l < selectForeignPokemon[0].length; l++) {
                        selectForeignPokemon1[l].setBorder(null);
                    }
                }
                selectForeignPokemon[i][j].setBorder(BorderFactory.createLineBorder(Color.yellow));
                foreignPokemonName.setText("Nombre: " + pokedexForeign[i][j].getName());
                foreignPokemonType1.setText("Tipo 1: " + pokedexForeign[i][j].getType1());
                foreignPokemonType2.setText("Tipo 2: " + pokedexForeign[i][j].getType2());
                foreignPokemonEggGroup1.setText("Huevo grupo 1: " + pokedexForeign[i][j].getEggGroup1());
                foreignPokemonEggGroup2.setText("Huevo grupo 2: " + pokedexForeign[i][j].getEggGroup2());
                foreignPokemonOriginalCoach.setText("Entrenador original: " + pokedexForeign[i][j].getOriginalCoach());
                foreignPokemonCoach.setText("Entrenador actual: " + pokedexForeign[i][j].getCoach());
            }
        });
        pokemonOringinImages = new JLabel[3][2];
        pokemonOriginNames = new JLabel[3][2];
        
        pokemonForeignImages = new JLabel[3][2];
        pokemonForeignNames = new JLabel[3][2];
        
        selectOriginPokemon = new JPanel[3][2];
        selectForeignPokemon = new JPanel[3][2];
        
        pokedexOrigin = new Pokemon[3][2];
        pokedexForeign = new Pokemon[3][2];
        
        this.originCoachNumber = 0;
        this.foreignCoachNumber = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        loginConnectionPane = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        enterExistingPlayerPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        coachNumberTextField = new javax.swing.JTextField();
        createPlayerLabel = new javax.swing.JLabel();
        createPlayerPane = new javax.swing.JPanel();
        originPlayerPokemonsPanel = new javax.swing.JPanel();
        foreingPlayerPokemonsPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        originPokemonName = new javax.swing.JLabel();
        originPokemonType1 = new javax.swing.JLabel();
        originPokemonType2 = new javax.swing.JLabel();
        originPokemonEggGroup1 = new javax.swing.JLabel();
        originPokemonEggGroup2 = new javax.swing.JLabel();
        originPokemonOriginalCoach = new javax.swing.JLabel();
        originPokemonCoach = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        foreingCoachNumberTxtField = new javax.swing.JTextField();
        searchForeignCoachBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        foreignPokemonName = new javax.swing.JLabel();
        foreignPokemonType1 = new javax.swing.JLabel();
        foreignPokemonType2 = new javax.swing.JLabel();
        foreignPokemonEggGroup1 = new javax.swing.JLabel();
        foreignPokemonEggGroup2 = new javax.swing.JLabel();
        foreignPokemonOriginalCoach = new javax.swing.JLabel();
        foreignPokemonCoach = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1152, 864));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1152, 864));

        loginConnectionPane.setBackground(new java.awt.Color(255, 255, 255));
        loginConnectionPane.setPreferredSize(new java.awt.Dimension(1152, 864));
        loginConnectionPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        loginConnectionPane.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 100, 40));

        jButton2.setText("Crear jugador");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        loginConnectionPane.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, -1, 40));

        jLabel1.setText("Seleccione la opción de ingreso");
        loginConnectionPane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, -1));

        enterExistingPlayerPane.setBackground(new java.awt.Color(255, 255, 255));
        enterExistingPlayerPane.setPreferredSize(new java.awt.Dimension(1152, 864));
        enterExistingPlayerPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Ingrese su número de entrenador");
        enterExistingPlayerPane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        loginBtn.setText("Ingresar");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        enterExistingPlayerPane.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));
        enterExistingPlayerPane.add(coachNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 150, -1));

        createPlayerLabel.setBackground(new java.awt.Color(0, 0, 0));
        createPlayerLabel.setForeground(new java.awt.Color(0, 0, 204));
        createPlayerLabel.setText("Crear jugador");
        createPlayerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createPlayerLabelMouseClicked(evt);
            }
        });
        enterExistingPlayerPane.add(createPlayerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 90, -1));

        createPlayerPane.setBackground(new java.awt.Color(255, 255, 255));
        createPlayerPane.setPreferredSize(new java.awt.Dimension(1152, 864));

        originPlayerPokemonsPanel.setBackground(new java.awt.Color(153, 204, 255));
        originPlayerPokemonsPanel.setPreferredSize(new java.awt.Dimension(450, 300));

        javax.swing.GroupLayout originPlayerPokemonsPanelLayout = new javax.swing.GroupLayout(originPlayerPokemonsPanel);
        originPlayerPokemonsPanel.setLayout(originPlayerPokemonsPanelLayout);
        originPlayerPokemonsPanelLayout.setHorizontalGroup(
            originPlayerPokemonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        originPlayerPokemonsPanelLayout.setVerticalGroup(
            originPlayerPokemonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        foreingPlayerPokemonsPanel.setBackground(new java.awt.Color(153, 204, 255));
        foreingPlayerPokemonsPanel.setPreferredSize(new java.awt.Dimension(450, 300));

        javax.swing.GroupLayout foreingPlayerPokemonsPanelLayout = new javax.swing.GroupLayout(foreingPlayerPokemonsPanel);
        foreingPlayerPokemonsPanel.setLayout(foreingPlayerPokemonsPanelLayout);
        foreingPlayerPokemonsPanelLayout.setHorizontalGroup(
            foreingPlayerPokemonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        foreingPlayerPokemonsPanelLayout.setVerticalGroup(
            foreingPlayerPokemonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        originPokemonName.setText("Nombre: ");

        originPokemonType1.setText("Tipo 1:");

        originPokemonType2.setText("Tipo 2:");

        originPokemonEggGroup1.setText("Huevo grupo 1:");

        originPokemonEggGroup2.setText("Huevo grupo 2:");

        originPokemonOriginalCoach.setText("Entrenador original:");

        originPokemonCoach.setText("Entrenador actual:");

        jLabel4.setText("Pokemon origin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(originPokemonType1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(originPokemonName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(originPokemonType2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(originPokemonEggGroup1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(originPokemonEggGroup2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(originPokemonOriginalCoach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(originPokemonCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(originPokemonName)
                .addGap(18, 18, 18)
                .addComponent(originPokemonType1)
                .addGap(18, 18, 18)
                .addComponent(originPokemonType2)
                .addGap(18, 18, 18)
                .addComponent(originPokemonEggGroup1)
                .addGap(18, 18, 18)
                .addComponent(originPokemonEggGroup2)
                .addGap(18, 18, 18)
                .addComponent(originPokemonOriginalCoach)
                .addGap(18, 18, 18)
                .addComponent(originPokemonCoach)
                .addContainerGap())
        );

        jButton3.setText("Intercambiar Pokemon");

        jLabel3.setText("Encontrar entrenador");

        searchForeignCoachBtn.setText("Buscar");
        searchForeignCoachBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchForeignCoachBtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        foreignPokemonName.setText("Nombre: ");

        foreignPokemonType1.setText("Tipo 1:");

        foreignPokemonType2.setText("Tipo 2:");

        foreignPokemonEggGroup1.setText("Huevo grupo 1:");

        foreignPokemonEggGroup2.setText("Huevo grupo 2:");

        foreignPokemonOriginalCoach.setText("Entrenador original:");

        foreignPokemonCoach.setText("Entrenador actual:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(foreignPokemonType1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(foreignPokemonName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(foreignPokemonType2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(foreignPokemonEggGroup1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(foreignPokemonEggGroup2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(foreignPokemonOriginalCoach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(foreignPokemonCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(foreignPokemonName)
                    .addGap(18, 18, 18)
                    .addComponent(foreignPokemonType1)
                    .addGap(18, 18, 18)
                    .addComponent(foreignPokemonType2)
                    .addGap(18, 18, 18)
                    .addComponent(foreignPokemonEggGroup1)
                    .addGap(18, 18, 18)
                    .addComponent(foreignPokemonEggGroup2)
                    .addGap(18, 18, 18)
                    .addComponent(foreignPokemonOriginalCoach)
                    .addGap(18, 18, 18)
                    .addComponent(foreignPokemonCoach)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );

        jLabel5.setText("Tu lista de pokemons");

        jLabel6.setText("Lista de pokemones otro entrenador");

        javax.swing.GroupLayout createPlayerPaneLayout = new javax.swing.GroupLayout(createPlayerPane);
        createPlayerPane.setLayout(createPlayerPaneLayout);
        createPlayerPaneLayout.setHorizontalGroup(
            createPlayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPlayerPaneLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(createPlayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(originPlayerPokemonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foreingPlayerPokemonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(createPlayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createPlayerPaneLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(createPlayerPaneLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(createPlayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(createPlayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createPlayerPaneLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(createPlayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(createPlayerPaneLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addGap(176, 176, 176))
                                    .addGroup(createPlayerPaneLayout.createSequentialGroup()
                                        .addComponent(foreingCoachNumberTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(createPlayerPaneLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(searchForeignCoachBtn)
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(createPlayerPaneLayout.createSequentialGroup()
                .addGroup(createPlayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createPlayerPaneLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel5))
                    .addGroup(createPlayerPaneLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel6)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        createPlayerPaneLayout.setVerticalGroup(
            createPlayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPlayerPaneLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createPlayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(originPlayerPokemonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(createPlayerPaneLayout.createSequentialGroup()
                        .addGroup(createPlayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createPlayerPaneLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(foreingCoachNumberTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchForeignCoachBtn))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createPlayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(foreingPlayerPokemonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(loginConnectionPane, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(enterExistingPlayerPane, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(createPlayerPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(loginConnectionPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 100, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(enterExistingPlayerPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(createPlayerPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1101, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(loginConnectionPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(enterExistingPlayerPane, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(createPlayerPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loginConnectionPane.setVisible(false);
        enterExistingPlayerPane.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void createPlayerView() {
        createPlayerPane.setVisible(true);
        enterExistingPlayerPane.setVisible(false);
        loginConnectionPane.setVisible(false);

        for (int i = 0; i < pokemonOringinImages.length; i++) {
            for (int j = 0; j < pokemonOringinImages.length - 1; j++) {
                //Jugador local
                pokemonOringinImages[i][j] = new JLabel();
                originPlayerPokemonsPanel.add(pokemonOringinImages[i][j]).setBounds((i * 150) + 25, (j * 150), 150, 150);

                pokemonOriginNames[i][j] = new JLabel();
                originPlayerPokemonsPanel.add(pokemonOriginNames[i][j]).setBounds((i * 150) + 50, (j * 150), 100, 25);

                selectOriginPokemon[i][j] = new JPanel();
                originPlayerPokemonsPanel.add(selectOriginPokemon[i][j]).setBounds((i * 150) + 11, (j * 140) + 12, 130, 130);
                selectOriginPokemon[i][j].setOpaque(false);
                
                //Jugador externo                
                pokemonForeignImages[i][j] = new JLabel();
                foreingPlayerPokemonsPanel.add(pokemonForeignImages[i][j]).setBounds((i * 150) + 25, (j * 150), 150, 150);

                pokemonForeignNames[i][j] = new JLabel();
                foreingPlayerPokemonsPanel.add(pokemonForeignNames[i][j]).setBounds((i * 150) + 50, (j * 150), 100, 25);
                
                selectForeignPokemon[i][j] = new JPanel();
                foreingPlayerPokemonsPanel.add(selectForeignPokemon[i][j]).setBounds((i * 150) + 11, (j * 140) + 12, 130, 130);
                selectForeignPokemon[i][j].setOpaque(false);
            }
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        createPlayerView();
        client = new Client(CREATE_NEW_PLAYER);
        client.getOriginPlayerHandler().addObserver(this);
        client.start();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void createPlayerLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createPlayerLabelMouseClicked
        createPlayerView();
        client = new Client(CREATE_NEW_PLAYER);
        client.getOriginPlayerHandler().addObserver(this);
        client.start();
    }//GEN-LAST:event_createPlayerLabelMouseClicked

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        try {
            if (!"".equals(coachNumberTextField.getText())) {
                createPlayerView();
                int coachNumberToFind = Integer.parseInt(coachNumberTextField.getText());
                client = new Client(LOAD_EXISTING_PLAYER, coachNumberToFind);
                client.getOriginPlayerHandler().addObserver(this);
                client.start();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El número de entrenador ingresado es incorrecto");
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void searchForeignCoachBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchForeignCoachBtnActionPerformed
        try {
            if (!"".equals(foreingCoachNumberTxtField.getText())) {
                int coachNumberToFind = Integer.parseInt(foreingCoachNumberTxtField.getText());
                client = new Client(LOAD_FOREIGN_PLAYER, coachNumberToFind);
                client.getForeignPlayerHandler().addObserver(this);
                client.start();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El número de entrenador ingresado es incorrecto");
        }
    }//GEN-LAST:event_searchForeignCoachBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField coachNumberTextField;
    private javax.swing.JLabel createPlayerLabel;
    private javax.swing.JPanel createPlayerPane;
    private javax.swing.JPanel enterExistingPlayerPane;
    private javax.swing.JLabel foreignPokemonCoach;
    private javax.swing.JLabel foreignPokemonEggGroup1;
    private javax.swing.JLabel foreignPokemonEggGroup2;
    private javax.swing.JLabel foreignPokemonName;
    private javax.swing.JLabel foreignPokemonOriginalCoach;
    private javax.swing.JLabel foreignPokemonType1;
    private javax.swing.JLabel foreignPokemonType2;
    private javax.swing.JTextField foreingCoachNumberTxtField;
    private javax.swing.JPanel foreingPlayerPokemonsPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel loginConnectionPane;
    private javax.swing.JPanel originPlayerPokemonsPanel;
    private javax.swing.JLabel originPokemonCoach;
    private javax.swing.JLabel originPokemonEggGroup1;
    private javax.swing.JLabel originPokemonEggGroup2;
    private javax.swing.JLabel originPokemonName;
    private javax.swing.JLabel originPokemonOriginalCoach;
    private javax.swing.JLabel originPokemonType1;
    private javax.swing.JLabel originPokemonType2;
    private javax.swing.JButton searchForeignCoachBtn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        if (o instanceof OriginPlayerHandler) {
            originCoach = (Player) arg;
            if (originCoach != null) {
                Pokemon pokemon;
                int k = 0;
                for (int i = 0; i < pokemonOringinImages.length; i++) {
                    for (int j = 0; j < pokemonOringinImages.length - 1; j++) {
                        pokemon = originCoach.getPokedex()[k++];
                        pokemonOringinImages[i][j].setIcon(new ImageIcon(getClass().getResource(pokemon.getImage())));
                        pokemonOriginNames[i][j].setText(pokemon.getName());
                        pokedexOrigin[i][j] = pokemon;
                    }
                }
                originCoachNumber = client.getPlayer().getCoachNumber();
                JOptionPane.showMessageDialog(null, "Su número de entrenador es: " + originCoachNumber);
            } else {
                JOptionPane.showMessageDialog(null, "No existe el entrenador indicado");
            }
        } else if (o instanceof ForeignPlayerHandler){
            foreighCoach = (Player) arg;
            if (foreighCoach != null){                            
                Pokemon pokemon;
                int k = 0;
                for (int i = 0; i < pokemonForeignImages.length; i++) {
                    for (int j = 0; j < pokemonForeignImages.length - 1; j++) {
                        pokemon = foreighCoach.getPokedex()[k++];
                        pokemonForeignImages[i][j].setIcon(new ImageIcon(getClass().getResource(pokemon.getImage())));
                        pokemonForeignNames[i][j].setText(pokemon.getName());
                        pokedexForeign[i][j] = pokemon;
                    }
                }
                foreignCoachNumber = client.getPlayer().getCoachNumber();
            } else {
                JOptionPane.showMessageDialog(null, "No existe el entrenador indicado");
            }
        }
    }
}
